name: Delete AzureML Online Endpoint

on:
  # Manual trigger for execution
  workflow_dispatch:
  
  # Scheduled execution (runs at 10 PM JST every day)
  schedule:
    - cron: "0 13 * * *"  # Runs at 1 PM UTC, which is 10 PM JST

jobs:
  delete-azureml-endpoint:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure login using service principal credentials
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install Azure ML extension for CLI
      - name: Install Azure ML CLI extension
        run: |
          az extension add --name ml

      # Set the endpoint name directly as a fixed value
      - name: Set fixed endpoint name
        run: |
          echo "ENDPOINT_NAME=pf-rag-knowledge-endpoint" >> $GITHUB_ENV

      # Delete the AzureML online endpoint using Azure CLI
      - name: Delete AzureML Online Endpoint
        run: |
          az ml online-endpoint delete --name $ENDPOINT_NAME --yes
